[global.areas]

# Coordonnées à affiner
old = { name = "Ancienne banque", world = "V5", pos1 = [-4096, 0, -2500], pos2 = [-3120, 256, -1664] }
spawn = { name = "Auberge du spawn", world = "V5", pos1 = [-2130, 0, -19250], pos2 = [-2080, 256, -19279] }

[global.databases.prism]

pool_size = 2

[debug]

cors = "*"
